keys:
  - &rubikoid_wsl age1mw00fzy3tkap89dfn6y2znfllunqj63cn6yxjzepn5a09yv0gqas4uj6vf
  - &rubikoid_ly370 age15009xgu7ecm7nqsyesaftwlk4k9ct0pt3ah42nh2p3q3drp8j5ksakz07l
  - &ly370 age1mdq3cljs95r77lxsm8kafup38cd40wvgvgjwpls25w8plynmyaaqdznv5m
  - &vpn age1tmgzpzap852hze5wyvk5fvg9d6jejpq7rx99aav2apjyuh9c9vrsexkl39
  - &dedic age1hdl2xpvs6utk288xkt59jprwh3ppxvl54kdr95lmcmdhmdx8yqfss0ssw2
  - &kubic age1klfs6z8qk3pqhjv02mnu3pzx993u8cpj4c2r4lsqtfu6l56a6essjuuv4z

creation_rules:
  - path_regex: nix/secrets/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *ly370
          - *vpn
          - *dedic

  - path_regex: nix/secrets/vpn/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *vpn

  - path_regex: nix/secrets/ly370/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *ly370

  - path_regex: nix/secrets/rpi4/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl

  - path_regex: nix/secrets/dedic/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *dedic

  - path_regex: nix/secrets/kubic/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *kubic

  - path_regex: nix/secrets/dedic/step/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *dedic

  - path_regex: nix/secrets/dedic/step/(certs|keys)/[^/]+\.(|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *dedic
