keys:
  - &rubikoid_wsl age1mw00fzy3tkap89dfn6y2znfllunqj63cn6yxjzepn5a09yv0gqas4uj6vf
  - &rubikoid_ly370 age15009xgu7ecm7nqsyesaftwlk4k9ct0pt3ah42nh2p3q3drp8j5ksakz07l
  - &rubikoid_mbp14 age13exgcpuz3payg26n6hpn4etnaxg3eeht4maeggdppt6yu2lwxcys5rewgr
  - &wsl age1lvekna9v84cr0vtyrpnfluaf59mra656nr8kwmqragdzszr6ea2sszcn2t
  - &ly370 age1mdq3cljs95r77lxsm8kafup38cd40wvgvgjwpls25w8plynmyaaqdznv5m
  - &vpn age1tmgzpzap852hze5wyvk5fvg9d6jejpq7rx99aav2apjyuh9c9vrsexkl39
  - &dedic age1hdl2xpvs6utk288xkt59jprwh3ppxvl54kdr95lmcmdhmdx8yqfss0ssw2
  - &kubic age1klfs6z8qk3pqhjv02mnu3pzx993u8cpj4c2r4lsqtfu6l56a6essjuuv4z

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *wsl
          - *ly370
          - *vpn
          - *dedic
          - *kubic

  - path_regex: secrets/vpn/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *vpn

  - path_regex: secrets/ly370/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *ly370

  - path_regex: secrets/rpi4/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14

  - path_regex: secrets/dedic/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *dedic

  - path_regex: secrets/kubic/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *kubic

  - path_regex: secrets/dedic/step/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *dedic

  - path_regex: secrets/dedic/step/(certs|keys)/[^/]+\.(|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *dedic
