keys:
  - &rubikoid_wsl age1mw00fzy3tkap89dfn6y2znfllunqj63cn6yxjzepn5a09yv0gqas4uj6vf
  - &rubikoid_ly370 age15009xgu7ecm7nqsyesaftwlk4k9ct0pt3ah42nh2p3q3drp8j5ksakz07l
  - &rubikoid_mbp14 age13exgcpuz3payg26n6hpn4etnaxg3eeht4maeggdppt6yu2lwxcys5rewgr
  - &wsl age1lvekna9v84cr0vtyrpnfluaf59mra656nr8kwmqragdzszr6ea2sszcn2t
  - &ly370 age1mdq3cljs95r77lxsm8kafup38cd40wvgvgjwpls25w8plynmyaaqdznv5m
  - &vpn age1tdjhn9qjpudqtkegxe7mrgnz4ca7ztt85th5q6kg73zw2mmzzczskm5n2s
  - &dedic age1hdl2xpvs6utk288xkt59jprwh3ppxvl54kdr95lmcmdhmdx8yqfss0ssw2
  - &kubic age1klfs6z8qk3pqhjv02mnu3pzx993u8cpj4c2r4lsqtfu6l56a6essjuuv4z
  - &mbp14 age1mutjl6uly4cgaj6qdge0me3e78z90hh35e55rjhw9vssspfttqqsjwq837
  - &yatb-kube-master age16xhh9cq9x8s6zy8ag9jjv4fw3tn8xj4xcr8u40pdmkzzesqe446qcrcj4j
  - &orb-nix age10mcqfg8tde8y6tc7zxz8d7sj2y2mq4d72hz3e079jyn7zln6vqgqfvem4u
  - &ext-ha age1ympkeang73dftvx5s0slfrn35zpavjn53mhd6gn823h20nsncyzqrqfh0m

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *wsl
          - *ly370
          - *vpn
          - *dedic
          - *kubic
          - *mbp14
          - *yatb-kube-master
          - *orb-nix
          - *ext-ha

  - path_regex: secrets/hosts/vpn/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *vpn

  - path_regex: secrets/hosts/ly370/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *ly370

  - path_regex: secrets/hosts/rpi4/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14

  - path_regex: secrets/hosts/dedic/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *dedic

  - path_regex: secrets/hosts/kubic/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *kubic

  - path_regex: secrets/hosts/dedic/step/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *dedic

  - path_regex: secrets/hosts/dedic/step/(certs|keys)/[^/]+\.(|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *dedic

  - path_regex: secrets/hosts/rubi-mbp14/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *mbp14

  - path_regex: secrets/hosts/r7-wsl/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *wsl

  - path_regex: secrets/hosts/yatb-kube-master/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *yatb-kube-master

  - path_regex: secrets/hosts/orb-nix/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *orb-nix

  - path_regex: secrets/hosts/ext-ha/[^/]+\.(yaml|json|env|ini|hjson|bin|conf|sh|crt|pub|key)$
    key_groups:
      - age:
          - *rubikoid_ly370
          - *rubikoid_wsl
          - *rubikoid_mbp14
          - *ext-ha
