# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [ ] }:
let
  version = "8c76a20";
  revision = "8c76a208ed30cc1bd54262302b2aed27ae142509";
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
      rev = "${revision}";
      hash = "sha256-8Kxm4BIvUsBsCWOEtc1FWoMtUAcQ+qINZ1usALNZ738=";
    };
    patches = patches ++ [ ./yarn-typescript.patch ];
  }) // {
  inherit version;
  yarnHash = "sha256-CIIz5wwWzvDKc/VbSIT7Z5D9kwOLoErXoO0WQWfV/g4=";
}
