# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
  version = "bb3ad2b";
  revision = "bb3ad2b2a93edd251b4ddf5b1b3f6bbe8a432009";
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
      rev = "${revision}";
      hash = "sha256-MJQIwZavPhEMhleSsIMn5LqNNv+8EYln11cR3/qN/wo=";
    };
    patches = patches ++ [];
  }) // {
  inherit version;
  yarnHash = "sha256-I6BO/IWwOCGr6V7FyVIBOq7Qt4KZA1WI/vpNYSYD9sQ=";
}
