# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
  version = "486e4bc";
  revision = "486e4bc7d3d3dd0c61de2eb316db841a222e36bf";
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
      rev = "${revision}";
      hash = "sha256-6awTDClg3alks/H+tEI7uf942B20uHRb3n9JsQxTy40=";
    };  
    patches = patches ++ [./yarn-typescript.patch];
  }) // {
  inherit version;
  yarnHash = "sha256-CIIz5wwWzvDKc/VbSIT7Z5D9kwOLoErXoO0WQWfV/g4=";
}
